image: docker/compose:latest
services:
  - docker:dind
stages:
  - build
  - deploy

build_app:
  image: node:12
  stage: build
  only:
    - master
  script:
    - ls -la
#    - npm install
#    - npm run build
    - touch yes.txt
#  cache:
#    paths:
#      - node_modules/
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour

step-deploy-prod:
  stage: deploy
  dependencies:
    - build_app
  script:
    - ls -la

step-deploy-dev:
  stage: deploy
  script:
    - docker stop node-server
    - docker rm node-server
    - docker build -t app/node-web-app .
    - docker run --name node-server -p 49162:8080 -p 49164:8081 -d app/node-web-app:latest sh -c 'npm run serve'
  only:
    - DEV
  tags:
    - DEV
  variables:
    ENVIRONMENT: development
    VUE_APP_API: https://api-test.urrobot.net
