image: docker/compose:latest
services:
  - docker:dind
stages:
  - deploy

step-deploy-prod:
  stage: deploy
  script:
    - docker stop node-server
    - docker rm node-server
    - docker build -t app/node-web-app .
    - docker run --name node-server -p 49162:8080 -p 49164:8081 -d app/node-web-app:latest sh -c 'tail -f'
    - docker cp node-server:/app/dist /home/gitlab-runner/dist
    - docker stop node-server
  only:
    - DEV
  tags:
    - DEV
  variables:
    ENVIRONMENT: production
    VUE_APP_API: https://api-2.urrobot.net


step-deploy-dev:
  stage: deploy
  script:
    - docker stop node-server
    - docker rm node-server
    - docker build -t app/node-web-app .
    - docker run --name node-server -p 49162:8080 -p 49164:8081 -d app/node-web-app:latest sh -c 'tail -f'
    - docker cp node-server:/app/dist /home/gitlab-runner/dist
    - docker stop node-server
  only:
    - DEV
  tags:
    - DEV
  variables:
    ENVIRONMENT: development
    VUE_APP_API: https://api-test.urrobot.net
