image: docker/compose:latest
services:
  - docker:dind
stages:
  - deploy

step-deploy-prod:
  stage: deploy
  script:
    - docker build -t app/node-web-app .
  only:
    - master
  tags:
    - master
  variables:
    ENVIRONMENT: production
    VUE_APP_API: https://api-2.urrobot.net
  artifacts:
    expire_in: 1 week
    paths:
      - dist


step-deploy-dev:
  stage: deploy
  script:
    - docker stop node-server
    - docker rm node-server
    - docker build -t app/node-web-app .
    - docker run --name node-server -p 49162:8080 -p 49164:8081 -d app/node-web-app:latest sh -c 'npm run serve'
  only:
    - DEV
  tags:
    - DEV
  variables:
    ENVIRONMENT: development
    VUE_APP_API: https://api-test.urrobot.net
