version: "3.5"

services:
  app:
    container_name: front-end-develop
    image: node:12-alpine
    command: sh -c "yarn install && yarn build && yarn add @sentry/vue @sentry/tracing"
    working_dir: /app
    volumes:
      - ./:/app
